name: BalenaCloud Fleet Deploy (Production)

on:
  schedule:
    - cron:  "0 0 * * *" # Run daily at midnight
  workflow_dispatch:

permissions: 
  contents: write

env:
  fleet: replace/with-your-fleet-slug
  
jobs:
  build-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check if new version of docker-compose.yml
        run: |
          cd /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}

          miner="$(echo ${{ github.event.repository.name }})"
          echo "Repo: $miner"
          echo "miner=$miner" >> $GITHUB_ENV

          wget https://raw.githubusercontent.com/NebraLtd/"$miner"/master/docker-compose.yml -O docker-compose.yml.new

          if cmp docker-compose.yml docker-compose.yml.new; then
            echo "We're already using the latest docker-compose.yml"
            echo "LATEST=TRUE" >> $GITHUB_ENV
            rm -f docker-compose.yml.new
            exit 0
          else
            echo "We're not using the latest docker-compose.yml. Updating..."
            echo "LATEST=FALSE" >> $GITHUB_ENV
            rm -f docker-compose.yml.new
            exit 0
          fi

      - name: Check for new version and pull updated files if necessary
        if: env.LATEST == 'FALSE'
        run: |
          cd /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}

          rm -f balena.yml
          rm -f config.txt
          rm -f docker-compose.yml
          rm -f ssh_public_keys.json
          rm -f .github/workflows/update-action-test.yml

          wget https://raw.githubusercontent.com/NebraLtd/"${{ env.miner }}"/master/balena.yml -O balena.yml
          wget https://raw.githubusercontent.com/NebraLtd/"${{ env.miner }}"/master/docker-compose.yml -O docker-compose.yml
          wget https://raw.githubusercontent.com/NebraLtd/"${{ env.miner }}"/master/config.txt -O config.txt
          wget https://raw.githubusercontent.com/NebraLtd/"${{ env.miner }}"/master/ssh_public_keys.json -O ssh_public_keys.json
          wget https://raw.githubusercontent.com/NebraLtd/"${{ env.miner }}"/master/workflows/update-action-prod.yml -O .github/workflows/update-action-prod.yml

      - name: Balena Deploy
        if: env.LATEST == 'FALSE'
        uses: nebraltd/balena-cli-action@v16.6.3
        with:
          balena_api_token: ${{secrets.BALENA_API_TOKEN}}
          balena_command: "deploy ${{ env.fleet }} --debug --nocache --build"

      - name: Push updated docker compose and balena.yml files
        if: env.LATEST == 'FALSE'
        uses: test-room-7/action-update-file@v1
        with:
          branch: master
          file-path: |
            *.yml
            config.*
            .github/workflows/*.yml
            ssh_public_keys.json
          commit-msg: Update docker-compose and other core files (production)
          github-token: ${{ secrets.GITHUB_TOKEN }}
