name: Manually trigger build action in OpenFleet repos

on:
  workflow_dispatch:

jobs:
  file-update:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sbc: [nebra-indoor1, nebra-outdoor1, nebra-indoor2, nebra-outdoor2, rak, pisces, og, sensecap, finestra, controllino, cotx, pantherx1, linxdot, linxdot-rkcm3, pycom, syncrobit, syncrobit-rkcm3, risinghf, midas, bobcat-px30]
    steps:
      - name: Generate repo name
        run: |
          FLEET="helium-${{ matrix.sbc }}"
          echo "FLEET=$FLEET" >> $GITHUB_ENV

      - name: Trigger build action in ${{ env.REPO }} repo
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.MR_BUMP }}
          event-type: build-open-fleet
          repository: NebraLtd/${{ env.FLEET }}
          client-payload: '{"release": "v1.0.2-40_GA", "tag": "v1.0.2-40", "firmware": "4bec138", "branch": "production"}'
