name: Manually trigger build action in OpenFleet repos

on:
  workflow_dispatch:

jobs:
  file-update:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sbc: [bobcat-px30]
    steps:
      - name: Generate repo name
        run: |
          FLEET="helium-${{ matrix.sbc }}"
          echo "FLEET=$FLEET" >> $GITHUB_ENV

      - name: Trigger build action in ${{ env.REPO }} repo
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.MR_BUMP }}
          event-type: build-open-fleet
          repository: NebraLtd/${{ env.FLEET }}
          client-payload: '{"release": "v1.0.2-40_GA", "tag": "v1.0.2-40", "firmware": "4bec138", "branch": "production"}'
