name: Update settings file in Commercial Fleets repo

on:
  push:
    paths:
      - 'settings.ini'
  workflow_dispatch:

jobs:
  file-update:
    if: github.ref_name == 'master' || github.ref_name == 'production' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger PR action in commercial-hotspot-software repo
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.MR_BUMP }}
          event-type: settings-update
          repository: NebraLtd/commercial-hotspot-software
          client-payload: '{"branch": "${{ github.ref_name }}"}'
