name: Update files in OpenFleets repos

on:
  push:
    paths:
      - 'settings.ini'
      - 'balena/**'
  workflow_dispatch:

jobs:
  file-update:
    if: github.ref_name == 'master' || github.ref_name == 'production' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sbc: [hnt_openfleet_template, nebra-indoor1, nebra-outdoor1, nebra-indoor2, nebra-outdoor2, rak, pisces, og, sensecap, finestra, controllino, cotx, pantherx1, linxdot, linxdot-rkcm3, pycom, syncrobit, syncrobit-rkcm3, risinghf, midas, bobcat-px30]
    steps:
      - name: Generate repo name
        run: |
          if [ "${{ matrix.sbc }}" = "hnt_openfleet_template" ]; then
            FLEET="${{ matrix.sbc }}"
          else
            FLEET="helium-${{ matrix.sbc }}"
          fi
          
          echo "FLEET=$FLEET" >> $GITHUB_ENV
         
      - name: Trigger PR action in ${{ env.FLEET }} repo
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.MR_BUMP }}
          event-type: file-update
          repository: NebraLtd/${{ env.FLEET }}
