name: BalenaCloud Deploy (Production - Draft Deploy)

on:
  workflow_dispatch:

jobs:
  build-prod:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sbc: [raspi, rockpi, rak, pisces, og, sensecap, finestra, controllino, cotx, pantherx1, linxdot, linxdot-rkcm3, pycom, syncrobit, syncrobit-rkcm3, risinghf]
        frequency: [470, 868, 915]
        variant: [indoor, outdoor]
        commercial: [yes, no]
        exclude:
          - sbc: rak
          - sbc: pisces
          - sbc: og
          - sbc: sensecap
          - sbc: finestra
          - sbc: controllino
          - sbc: cotx
          - sbc: pantherx1
          - sbc: linxdot
          - sbc: linxdot-rkcm3
          - sbc: syncrobit
          - sbc: syncrobit-rkcm3
          - sbc: pycom
          - sbc: risinghf
          - sbc: rockpi
            variant: outdoor
            commercial: yes
          - variant: indoor
            commercial: yes
            frequency: 470
          - sbc: raspi
            commercial: yes
            frequency: 470
        include:
          - sbc: pisces
            variant: indoor
            frequency: 868
            commercial: no
          - sbc: rak
            variant: indoor
            frequency: 868
            commercial: no
          - sbc: og
            variant: indoor
            frequency: 868
            commercial: no
          - sbc: sensecap
            variant: indoor
            frequency: 868
            commercial: no
          - sbc: finestra
            variant: indoor
            frequency: 868
            commercial: no
          - sbc: controllino
            variant: indoor
            frequency: 868
            commercial: no
          - sbc: cotx
            variant: indoor
            frequency: 868
            commercial: no
          - sbc: pantherx1
            variant: indoor
            frequency: 868
            commercial: no
          - sbc: linxdot
            variant: indoor
            frequency: 868
            commercial: no
          - sbc: linxdot-rkcm3
            variant: indoor
            frequency: 868
            commercial: no
          - sbc: syncrobit
            variant: indoor
            frequency: 868
            commercial: no
          - sbc: syncrobit-rkcm3
            variant: indoor
            frequency: 868
            commercial: no
          - sbc: pycom
            variant: indoor
            frequency: 868
            commercial: no
          - sbc: risinghf
            variant: indoor
            frequency: 868
            commercial: no
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: production
      - name: Export short SHA of current commit
        shell: bash
        run: |
          FIRMWARE_SHORT_HASH=$( echo ${GITHUB_SHA:0:7} )
          echo "FIRMWARE_SHORT_HASH=$FIRMWARE_SHORT_HASH" >> $GITHUB_ENV
          
          # Get the latest GA release and branch
          source <(grep FIRMWARE_VERSION settings.ini)
          LATEST_GA=$FIRMWARE_VERSION
          GITHUB_BRANCH=$( echo "${{ github.ref }}" | sed 's/refs\/heads\///g' )
          
          if [ "${{ matrix.commercial }}" = "yes" ] ; then
            echo " Deploying to commercial fleet!"
            COMMERCIAL="-c"
          fi
          
          echo "LATEST_GA=$LATEST_GA" >> $GITHUB_ENV
          echo "GITHUB_BRANCH=$GITHUB_BRANCH" >> $GITHUB_ENV
          echo "COMMERCIAL=$COMMERCIAL" >> $GITHUB_ENV
      - name: Random sleep (balena API workaround)
        run:  sleep $[ ( $RANDOM % 540 ) + 1 ]s
      - name: Generate Docker Compose for ROCK Pi
        if: matrix.sbc == 'rockpi'
        run: |
          python gen_docker_compose.py rockpi -o docker-compose.yml
          ROCKPI="-rockpi"
          echo "ROCKPI=$ROCKPI" >> $GITHUB_ENV
          cp balena/balena.yml.${{ matrix.sbc }}-${{ matrix.variant }} balena.yml
      - name: Generate Docker Compose for Nebra RasPi
        if: matrix.sbc == 'raspi'
        run: |
          python gen_docker_compose.py rpi -o docker-compose.yml
          cp balena/balena.yml.${{ matrix.sbc }}-${{ matrix.variant }} balena.yml
      - name: Generate Docker Compose for RAK and Non-Nebra RasPi
        if: matrix.sbc == 'rak' || matrix.sbc == 'og' || matrix.sbc == 'sensecap' || matrix.sbc == 'finestra' || matrix.sbc == 'controllino' || matrix.sbc == 'cotx' || matrix.sbc == 'pantherx1' || matrix.sbc == 'linxdot' || matrix.sbc == 'syncrobit' || matrix.sbc == 'risinghf'
        run: |
          python gen_docker_compose.py rpi -o docker-compose.yml
          cp balena/balena.yml.${{ matrix.sbc }} balena.yml
      - name: Generate Docker Compose for Non-Nebra ROCK Pi
        if: matrix.sbc == 'linxdot-rkcm3' || matrix.sbc == 'syncrobit-rkcm3'
        run: |
          python gen_docker_compose.py rockpi -o docker-compose.yml
          ROCKPI="-rockpi"
          echo "ROCKPI=$ROCKPI" >> $GITHUB_ENV
          cp balena/balena.yml.${{ matrix.sbc }} balena.yml
      - name: Generate Docker Compose for Pycom
        if: matrix.sbc == 'pycom'
        run: |
          python gen_docker_compose.py pycom -o docker-compose.yml
          cp balena/balena.yml.pycom balena.yml
      - name: Generate Docker Compose for Pisces
        if: matrix.sbc == 'pisces'
        run: |
          python gen_docker_compose.py pisces -o docker-compose.yml
          cp balena/balena.yml.pisces balena.yml
      - name: Balena Deploy (Nebra ROCK Pi)
        uses: nebraltd/balena-cli-action@v15.0.3
        if: matrix.sbc == 'rockpi' && matrix.commercial == 'no' && success()
        with:
          balena_api_token: ${{secrets.BALENA_API_TOKEN}}
          balena_command: "deploy nebraltd/helium-${{ matrix.variant }}-${{ matrix.frequency }}${{ env.ROCKPI }} --debug --nocache --build --draft"
      - name: Balena Deploy (Nebra RasPi)
        uses: nebraltd/balena-cli-action@v15.0.3
        if: matrix.sbc == 'raspi' && matrix.commercial == 'no' && success()
        with:
          balena_api_token: ${{secrets.BALENA_API_TOKEN_1}}
          balena_command: "deploy nebraltd/helium-${{ matrix.variant }}-${{ matrix.frequency }} --debug --nocache --build --draft"
      - name: Balena Deploy (Nebra ROCK Pi Commercial)
        uses: nebraltd/balena-cli-action@v15.0.3
        if: matrix.sbc == 'rockpi' && matrix.commercial == 'yes' && success()
        with:
          balena_api_token: ${{secrets.BALENA_API_TOKEN_2}}
          balena_command: "deploy nebraltd/helium-${{ matrix.variant }}-${{ matrix.frequency }}${{ env.ROCKPI }}${{ env.COMMERCIAL }} --debug --nocache --build --draft"
      - name: Balena Deploy (Nebra RasPi Commercial)
        uses: nebraltd/balena-cli-action@v15.0.3
        if: matrix.sbc == 'raspi' && matrix.commercial == 'yes' && success()
        with:
          balena_api_token: ${{secrets.BALENA_API_TOKEN_3}}
          balena_command: "deploy nebraltd/helium-${{ matrix.variant }}-${{ matrix.frequency }}${{ env.COMMERCIAL }} --debug --nocache --build --draft"
      - name: Balena Deploy (RAK and Non-Nebra RasPi)
        uses: nebraltd/balena-cli-action@v15.0.3
        if: ( matrix.sbc == 'rak' || matrix.sbc == 'og' || matrix.sbc == 'sensecap' || matrix.sbc == 'finestra' || matrix.sbc == 'controllino' || matrix.sbc == 'cotx' || matrix.sbc == 'pantherx1' || matrix.sbc == 'linxdot' || matrix.sbc == 'syncrobit' || matrix.sbc == 'risinghf' ) && success()
        with:
          balena_api_token: ${{secrets.BALENA_API_TOKEN_4}}
          balena_command: "deploy nebraltd/helium-${{ matrix.sbc }} --debug --nocache --build --draft"
      - name: Balena Deploy (Non-Nebra ROCK Pi)
        uses: nebraltd/balena-cli-action@v15.0.3
        if: ( matrix.sbc == 'linxdot-rkcm3' || matrix.sbc == 'syncrobit-rkcm3' ) && success()
        with:
          balena_api_token: ${{secrets.BALENA_API_TOKEN_5}}
          balena_command: "deploy nebraltd/helium-${{ matrix.sbc }} --debug --nocache --build --draft"
      - name: Balena Deploy (Pycom CM4)
        uses: nebraltd/balena-cli-action@v15.0.3
        if: matrix.sbc == 'pycom' && success()
        with:
          balena_api_token: ${{secrets.BALENA_API_TOKEN_6}}
          balena_command: "deploy nebraltd/helium-${{ matrix.sbc }} --debug --nocache --build --draft"
      - name: Balena Deploy (Pisces P100)
        uses: nebraltd/balena-cli-action@v15.0.3
        if: matrix.sbc == 'pisces' && success()
        with:
          balena_api_token: ${{secrets.BALENA_API_TOKEN_7}}
          balena_command: "deploy nebraltd/helium-${{ matrix.sbc }} --debug --nocache --build --draft"
      - name: Trigger build action in helium-${{ matrix.sbc }} repo
        uses: peter-evans/repository-dispatch@v2
        if: ( matrix.sbc == 'rak' || matrix.sbc == 'pisces' || matrix.sbc == 'og' || matrix.sbc == 'sensecap' || matrix.sbc == 'finestra' || matrix.sbc == 'controllino' || matrix.sbc == 'cotx' || matrix.sbc == 'pantherx1' || matrix.sbc == 'linxdot' || matrix.sbc == 'linxdot-rkcm3' || matrix.sbc == 'syncrobit' || matrix.sbc == 'syncrobit-rkcm3' || matrix.sbc == 'pycom' || matrix.sbc == 'risinghf' ) && success()
        with:
          token: ${{ secrets.MR_BUMP }}
          event-type: build-open-fleet
          repository: NebraLtd/helium-${{ matrix.sbc }}
          client-payload: '{"release": "${{ env.LATEST_GA }}_GA", "tag": "${{ env.LATEST_GA }}"}'
