name: BalenaCloud Deploy (Production - Draft Deploy)

on:
  workflow_dispatch:

jobs:
  build-prod:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        variant: [nebra-indoor1, nebra-outdoor1, nebra-indoor2, nebra-outdoor2, nebra-light1, nebra-light2, nebra-light3, cotx3-v1, finestra-v1, helium-v1, panther-v1, pisces-v1, rak-v1]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: production
      - name: Export short SHA of current commit
        run: |
          FIRMWARE_SHORT_HASH=$( echo ${GITHUB_SHA:0:7} )
          echo "FIRMWARE_SHORT_HASH=$FIRMWARE_SHORT_HASH" >> $GITHUB_ENV
      - name: Random sleep (balena API workaround)
        run:  sleep $[ ( $RANDOM % 360 ) + 1 ]s
      - name: Generate Docker Compose
        run: python gen_docker_compose.py -v ${{matrix.variant}} -o docker-compose.yml
      - name: Balena Deploy Mainnet
        uses: nebraltd/balena-cli-action@v13.3.0
          with:
            balena_api_token: ${{secrets.BALENA_API_TOKEN}}
            balena_command: "deploy nebraltd/${{ matrix.variant }}_mainnet_commercial --logs --debug --nocache --build --draft"