name: Code Security Audit

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
    - name: Run bandit against code base
      run: |
        pip install bandit
        bandit -r . -x "./tests/*"
